module.exports = {
modul: {
    axios: require('axios'),
    boom: require('@hapi/boom'),
    baileys: require("baileys"),
    chalk: require('chalk'),
    crypto: require('crypto'),
    cheerio: require('cheerio'),
    child_process: require('child_process'),
    cookie: require('cookie'),
    fs: require('fs'),
    fsx: require('fs-extra'),
    fetch: require('node-fetch'),
    figlet: require('figlet'),
    FormData: require('form-data'),
    FileType: require('file-type'),
    ffmpeg: require('fluent-ffmpeg'),
    got: require('got'),
    gimage: require('g-i-s'),
    google: require('google-it'),
    googleTTS: require('google-tts-api'),
    human: require('human-readable'),
    // jsobfus: require('javascript-obfuscator'), // REMOVED
    Jimp: require('jimp'),
    jsdom: require('jsdom'),
    keyeddb: require('@adiwajshing/keyed-db'),
    lodash: require('lodash'),
    moment: require('moment-timezone'),
    ms: require('ms'),
    miniget: require('miniget'),
    maker: require('mumaker'),
    nodecron: require('node-cron'),
    nodeid3: require('node-id3'),
    nodeytm: require('node-youtube-music'),
    os: require('os'),
    objectquery: require('object-query-string'),
    path: require('path'),
    perf_hooks: require('perf_hooks'),
    pino: require('pino'),
    parsems: require('parse-ms'),
    process: require('process'),
    PhoneNumber: require('awesome-phonenumber'),
    qs: require('qs'),
    qrcodeterminal: require('qrcode-terminal'),
    qrcode: require('qrcode'),
    // request: require('request'), // REMOVED (deprecated)
    scrapePrimbon: require('scrape-primbon'),
    speed: require('performance-now'),
    stream: require('stream'), // Native Node.js module
    // syntaxerror: require('syntax-error'), // REMOVED
    util: require('util'), // Native Node.js module
    yargs: require('yargs'),
    ytdlcr: require('youtubedl-core'),
    yts: require('yt-search'),
    yt: require('youtube-yts'),
    ytdl: require('ytdl-core'),
    webp: require('node-webpmux')
}
}
